version = 0.1

[default.deploy.parameters]
stack_name = "clouddesk-dev"
resolve_s3 = true
s3_prefix = "clouddesk-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\" CorsAllowedOrigin=\"http://localhost:5173\" LogLevel=\"INFO\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
